"""rename subscription table

Revision ID: 0ffddaed626c
Revises: 74e8a59d4b52
Create Date: 2025-05-13 20:54:42.267747

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0ffddaed626c"
down_revision: Union[str, None] = "74e8a59d4b52"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "subscriptions",
        sa.Column("follower_id", sa.Integer(), nullable=False),
        sa.Column("following_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["follower_id"],
            ["UserProfile.id"],
        ),
        sa.ForeignKeyConstraint(
            ["following_id"],
            ["UserProfile.id"],
        ),
        sa.PrimaryKeyConstraint("follower_id", "following_id"),
    )
    op.drop_table("subscription")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "subscription",
        sa.Column("follower_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("following_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["follower_id"], ["UserProfile.id"], name="subscription_follower_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["following_id"], ["UserProfile.id"], name="subscription_following_id_fkey"
        ),
        sa.PrimaryKeyConstraint(
            "follower_id", "following_id", name="subscription_pkey"
        ),
    )
    op.drop_table("subscriptions")
    # ### end Alembic commands ###
