"""fix db

Revision ID: 1daca10a6acf
Revises: b35644be6ca8
Create Date: 2025-05-11 18:22:44.788828

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1daca10a6acf"
down_revision: Union[str, None] = "b35644be6ca8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("Posts", "title")
    op.add_column("UserProfile", sa.Column("photo_url", sa.String(), nullable=True))
    op.drop_column("UserProfile", "photo")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "UserProfile",
        sa.Column("photo", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_column("UserProfile", "photo_url")
    op.add_column(
        "Posts", sa.Column("title", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
