"""add delete_photo_after_days

Revision ID: 42a48caaf175
Revises: 0ffddaed626c
Create Date: 2025-05-18 14:00:39.473878

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "42a48caaf175"
down_revision: Union[str, None] = "0ffddaed626c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "UserProfile",
        sa.Column(
            "delete_photo_after_days",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("UserProfile", "delete_photo_after_days")
    # ### end Alembic commands ###
