"""add delete_photo_after_days

Revision ID: 6da25c61c481
Revises: 42a48caaf175
Create Date: 2025-05-18 14:17:48.436236

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6da25c61c481"
down_revision: Union[str, None] = "42a48caaf175"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "UserSettings",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("delete_photo_after_days", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["UserProfile.id"],
        ),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.drop_column("UserProfile", "delete_photo_after_days")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "UserProfile",
        sa.Column(
            "delete_photo_after_days",
            sa.BOOLEAN(),
            server_default=sa.text("true"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_table("UserSettings")
    # ### end Alembic commands ###
