"""fix userprofile photo column

Revision ID: 74ada424232e
Revises: 6da25c61c481
Create Date: 2024-03-19 12:00:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "74ada424232e"
down_revision: Union[str, None] = "6da25c61c481"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("UserProfile") as batch_op:
        batch_op.alter_column("photo_url", nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("UserProfile") as batch_op:
        batch_op.alter_column("photo_url", nullable=False)
    # ### end Alembic commands ###
