"""

Revision ID: 74e8a59d4b52
Revises: d0fd9d251de9
Create Date: 2025-05-13 20:53:09.480845

"""

from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = "74e8a59d4b52"
down_revision: Union[str, None] = "d0fd9d251de9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
