"""init

Revision ID: 83a89a2dcdaa
Revises: 34b6e6ea1c0b
Create Date: 2025-05-28 10:43:48.680440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83a89a2dcdaa'
down_revision: Union[str, None] = '34b6e6ea1c0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('UserProfile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['UserProfile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('UserSettings',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('delete_photo_after_days', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['UserProfile.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('subscriptions',
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('following_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['follower_id'], ['UserProfile.id'], ),
    sa.ForeignKeyConstraint(['following_id'], ['UserProfile.id'], ),
    sa.PrimaryKeyConstraint('follower_id', 'following_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscriptions')
    op.drop_table('UserSettings')
    op.drop_table('Posts')
    op.drop_table('UserProfile')
    # ### end Alembic commands ###
