"""fix photo in UserProfile by settings nullable=True

Revision ID: b35644be6ca8
Revises: b41d3e92df6d
Create Date: 2025-05-11 17:32:58.000353

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b35644be6ca8"
down_revision: Union[str, None] = "b41d3e92df6d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("UserProfile", "photo", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("UserProfile", "photo", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
