"""

Revision ID: d0fd9d251de9
Revises: 1daca10a6acf
Create Date: 2025-05-13 20:08:15.775365

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d0fd9d251de9"
down_revision: Union[str, None] = "1daca10a6acf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "subscription",
        sa.Column("follower_id", sa.Integer(), nullable=False),
        sa.Column("following_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["follower_id"],
            ["UserProfile.id"],
        ),
        sa.ForeignKeyConstraint(
            ["following_id"],
            ["UserProfile.id"],
        ),
        sa.PrimaryKeyConstraint("follower_id", "following_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("subscription")
    # ### end Alembic commands ###
